### PR TITLE
Support \input and \subimport

### PR DESCRIPTION
**Pull request by mlq**

### CODE REVIEW

**Comment by misc0110** [comment]
Looks good, but can you also add \include?

**Comment by mlq** [comment]
Dear @misc0110 ,

Thank you for the suggestion! I've added the support of `\include` as well!

Best regards

**Comment by misc0110** [comment]
Dear @mlq,

I appreciate the quick response. You may want to consider incrementing the version number as well (https://github.com/misc0110/BibTool/blob/4aa6ce3b27f1246f1eee26aa6e7c577b7ab1da72/client.py#L12) to ensure all clients are automatically updated to your new version as soon as the server is updated.

**Comment by mlq** [comment]
Dear @misc0110,

Thank you for spotting this! I've added a new commit resolving this issue.

**Pull request merged**
